In [1]:
#PyTorch Tutorial

from __future__ import print_function
import torch

In [4]:
#Construct an unitialized matrix

x= torch.empty(5,4)
print(x)

tensor([[8.8910e-10, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.1019e-44, 0.0000e+00],
        [1.7047e+11, 7.6791e-43, 1.7047e+11, 7.6791e-43],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00]])


In [6]:
#Construct a randomly initialized matrix

x= torch.rand(5,4)
x

tensor([[0.1614, 0.4067, 0.9944, 0.0455],
        [0.2235, 0.8497, 0.5883, 0.6399],
        [0.4983, 0.6390, 0.6313, 0.8885],
        [0.6301, 0.9968, 0.0409, 0.5412],
        [0.4110, 0.9776, 0.8891, 0.3262]])

In [8]:
#Construct a matrix of zeros and dtype long

x= torch.zeros(5,4, dtype=torch.long)
x

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [13]:
#Construct a tensor directly from data
x= torch.tensor([[123, 12,434], [78,34,565]])
x

tensor([[123,  12, 434],
        [ 78,  34, 565]])

In [15]:
x= x.new_ones(5,3, dtype=torch.float32)
print(x)

x= torch.rand_like(x, dtype=torch.float32)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7269, 0.2901, 0.7192],
        [0.0833, 0.9956, 0.2926],
        [0.5292, 0.8346, 0.7613],
        [0.7603, 0.7655, 0.2390],
        [0.2283, 0.3864, 0.0855]])


In [16]:
#get size
print(x.size())

torch.Size([5, 3])


In [17]:
#Operations

y= torch.rand(5,3, dtype= torch.float32)
print(x+y)

tensor([[1.5844, 0.4125, 1.0837],
        [0.0914, 1.3033, 1.0860],
        [0.7434, 1.7218, 0.8757],
        [0.9431, 1.3939, 0.2818],
        [0.6661, 1.3445, 0.2698]])


In [18]:
print(torch.add(x,y))

tensor([[1.5844, 0.4125, 1.0837],
        [0.0914, 1.3033, 1.0860],
        [0.7434, 1.7218, 0.8757],
        [0.9431, 1.3939, 0.2818],
        [0.6661, 1.3445, 0.2698]])


In [20]:
#Addition: providing an output tensor as argument
z= torch.empty(5,3)
torch.add(x,y, out=z)
print(z)

tensor([[1.5844, 0.4125, 1.0837],
        [0.0914, 1.3033, 1.0860],
        [0.7434, 1.7218, 0.8757],
        [0.9431, 1.3939, 0.2818],
        [0.6661, 1.3445, 0.2698]])


In [21]:
#Addition: in place
y.add_(x)
print(y)


tensor([[1.5844, 0.4125, 1.0837],
        [0.0914, 1.3033, 1.0860],
        [0.7434, 1.7218, 0.8757],
        [0.9431, 1.3939, 0.2818],
        [0.6661, 1.3445, 0.2698]])


In [22]:
#Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [26]:
print(x[:,1])
print(x[0,:])

tensor([0.2901, 0.9956, 0.8346, 0.7655, 0.3864])
tensor([0.7269, 0.2901, 0.7192])


In [27]:
#Resizing: If you want to resize/reshape tensor, you can use torch.view

In [34]:
x= torch.randn(4,3)
print(x)
print(x.size())
print(x.view(12).view(12))
print(x.view(12).size())
print(x.view(-1,6))
print(x.view(-1,6).size())

tensor([[-1.9685,  0.3666, -0.5297],
        [ 0.1175,  0.9344, -0.7047],
        [-0.4696,  0.6898, -0.2717],
        [-1.1595, -1.0936,  0.3568]])
torch.Size([4, 3])
tensor([-1.9685,  0.3666, -0.5297,  0.1175,  0.9344, -0.7047, -0.4696,  0.6898,
        -0.2717, -1.1595, -1.0936,  0.3568])
torch.Size([12])
tensor([[-1.9685,  0.3666, -0.5297,  0.1175,  0.9344, -0.7047],
        [-0.4696,  0.6898, -0.2717, -1.1595, -1.0936,  0.3568]])
torch.Size([2, 6])


In [35]:
#If you have a one element tensor, use .item() to get the value as a Python number

In [40]:
x= torch.rand(1)
print(x)
print(x.item())

tensor([0.0152])
0.01520615816116333


In [46]:
#Numpy Bridge

a= torch.ones(5)
print(a)
b=a.numpy()
print(b)

#See how the numpy array changed in value
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [47]:
#Converting numpy array to tensor
import numpy as np
a = np.ones(5)
b= torch.from_numpy(a)

print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [49]:
#CUDA Tensors

# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!