In [1]:
#Autograd - To track the history of a tensor

import torch

In [16]:
#Create a tensor and set requires_grad=True to track computation with it

x= torch.ones([2,2], requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y=x+3

In [4]:
print(y.grad_fn)

In [5]:
print(y)

tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward>)


In [17]:
z=y+y*x
out=z.mean()
print(z, out)

tensor([[8., 8.],
        [8., 8.]], grad_fn=<ThAddBackward>) tensor(8., grad_fn=<MeanBackward1>)


In [11]:
# .requires_grad_( ... ) changes an existing Tensor’s requires_grad flag in-place. The input flag defaults to False if not given.

a= torch.rand([2,2])
a=a*3/7

In [13]:
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b= a*a+sum(a,a)
print(b.grad_fn)

False
True


In [18]:
#Gradients

out.backward()

#print gradients d(out)/dx
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [25]:
x= torch.rand(3, requires_grad=True)

y= x*2

while y.data.norm() < 1000:
    y=y*2
    
print(y)

tensor([663.4214, 487.2925, 874.5716], grad_fn=<MulBackward>)


In [26]:
print(x.requires_grad)
print((x**2).requires_grad)

#To stop autograd from tracking history
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
